version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset_202305:
    run: >
      ehrql:v0 generate-dataset analysis/dataset_definition.py --output output/dataset_202305.arrow
      -- --start 2023-05-01 --end 2023-05-31
    outputs:
      highly_sensitive:
        dataset: output/dataset_202305.arrow

  generate_dataset_202306:
    run: >
      ehrql:v0 generate-dataset analysis/dataset_definition.py --output output/dataset_202306.arrow
      -- --start 2023-06-01 --end 2023-06-30
    outputs:
      highly_sensitive:
        dataset: output/dataset_202306.arrow

  generate_dataset_202307:
    run: >
      ehrql:v0 generate-dataset analysis/dataset_definition.py --output output/dataset_202307.arrow
      -- --start 2023-07-01 --end 2023-07-31
    outputs:
      highly_sensitive:
        dataset: output/dataset_202307.arrow

  count:
    run: python:latest analysis/count.py
    needs: [generate_dataset_202305, generate_dataset_202306, generate_dataset_202307]
    outputs:
      moderately_sensitive:
        count: output/count.csv
