version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_dataset:
    run: >
      ehrql:v0 generate-dataset analysis/dataset_definition.py --output output/dataset.arrow
    outputs:
      highly_sensitive:
        dataset: output/dataset.arrow

  count:
    run: python:latest analysis/count.py
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        count: output/count.csv
